### ISSUE TITLE
webamp fix, breaks things

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#142]
Receiving various error in my console

2018-10-22T14:37:20.827Z info: Access mStream on your local network: https://10.1.1.131:3000
TypeError: Cannot read property 'count' of undefined
    at Object.exports.getNumberOfFiles (/home/dennis/mStream/modules/db-read/database-public-loki.js:84:29)
    at /home/dennis/mStream/modules/db-management/database-master.js:16:25
    at Layer.handle [as handle_request] (/home/dennis/mStream/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/dennis/mStream/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/dennis/mStream/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/dennis/mStream/node_modules/express/lib/router/layer.js:95:5)
    at /home/dennis/mStream/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/dennis/mStream/node_modules/express/lib/router/index.js:335:12)
    at next (/home/dennis/mStream/node_modules/express/lib/router/index.js:275:10)
    at jwt.verify (/home/dennis/mStream/modules/login.js:149:7)

**Comment by aroundmyroom** [comment]
restart did not show the issue in the console again, but cannot login anymore

**Comment by aroundmyroom** [comment]
Donate:
https://www.patreon.com/mstream

Find a bug? Report it at:
https://github.com/IrosTheBeggar/mStream/issues

Developed by Paul Sori

2018-10-22T14:41:13.526Z info: File scan started on /media/music/
2018-10-22T14:41:13.535Z info: Access mStream locally: https://localhost:3000
2018-10-22T14:41:13.706Z info: Access mStream on your local network: https://10.1.1.131:3000

2nd time start, but now the web interface is not shown anymore, looks like the db-management is consuming all resources

NB. I updated from update version to latest commit.
I now reverted back to the latest version 3.8.2, all is ok now (means, I am back at the update version)

**Comment by IrosTheBeggar** [comment]
I reverted the modified server code in the latest commit. Can you give that a try and let me know if it works

**Comment by aroundmyroom** [comment]
I just reverted back to the master and pulled all data from 25/10/18 and seems to work (I can login, have music)

**Comment by aroundmyroom** [comment]
will start new thread for latest commit
