### ISSUE TITLE
jukebox mode not playing music

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#143]
Entering valid code, see the music
try to play 1 song

![image](https://user-images.githubusercontent.com/250108/47494849-f094c680-d852-11e8-8420-963f4c66e563.png)

Access Denied on the path info.
Is there needed a config setting when using jukebox mode (allow no username?) or is this an issue?

**Comment by IrosTheBeggar** [comment]
Jukebox mode just got some updates.  The difference now is you can use a specific URL structure to tell the webapp to go into jukebox mode automatically:

www.yourdomain.com/j/abc
OR
www.yourdomain.com/?code=abc


I also updated the `ws` library from v1 to v6.  Try rerunning npm install to see if that fixes the problem

**Comment by aroundmyroom** [comment]
tried that /.. now mStream will not react to any request, the WEBUI is not even loaded.
Eve n High load on server.
first did npm install than npm link and restarted mStream.
..
update .. it took the webinterface around 7 minutes to 'start' after starting mStream. Looks like an initial re-scan of db caused to consume all resource (but the db is not being written to as it still has old timestamp)

141483 Oct 25 16:02 mstream.log
and website started to show login 16.09

and in the end still an access-denied like before on the jukebox, even in console mode refreshed cache to be sure no js would be not being updated

UI also very 'unresponsive' very slow (probably due to an database scan)

![image](https://user-images.githubusercontent.com/250108/47507369-5e9cb600-d872-11e8-8ebd-f65bfb1ef046.png)

**Comment by aroundmyroom** [comment]
all kinds of error in console;

TypeError: Assignment to constant variable.
    at mstream.post (/home/dennis/mStream/modules/jukebox.js:190:18)
    at Layer.handle [as handle_request] (/home/dennis/mStream/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/dennis/mStream/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/dennis/mStream/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/dennis/mStream/node_modules/express/lib/router/layer.js:95:5)
    at /home/dennis/mStream/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/dennis/mStream/node_modules/express/lib/router/index.js:335:12)
    at next (/home/dennis/mStream/node_modules/express/lib/router/index.js:275:10)
    at jwt.verify (/home/dennis/mStream/modules/login.js:149:7)
    at /home/dennis/mStream/node_modules/jsonwebtoken/verify.js:196:12
2018-10-25T14:16:02.280Z info: Websocket Connection Accepted With Code: 92659
TypeError: Assignment to constant variable.
    at mstream.post (/home/dennis/mStream/modules/jukebox.js:190:18)
    at Layer.handle [as handle_request] (/home/dennis/mStream/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/dennis/mStream/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/dennis/mStream/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/dennis/mStream/node_modules/express/lib/router/layer.js:95:5)
    at /home/dennis/mStream/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/dennis/mStream/node_modules/express/lib/router/index.js:335:12)
    at next (/home/dennis/mStream/node_modules/express/lib/router/index.js:275:10)
    at jwt.verify (/home/dennis/mStream/modules/login.js:149:7)
    at /home/dennis/mStream/node_modules/jsonwebtoken/verify.js:196:12
2018-10-25T14:22:16.203Z info: File scan message: database saved
2018-10-25T14:22:17.103Z info: File scan completed with code 0

**Comment by IrosTheBeggar** [comment]
I fixed the console errors.  Not sure what's going on with the slowness. Will look into it

**Comment by aroundmyroom** [comment]
dunno whats happening 
Just updated, and restarted, I immediate can login, see my folders. try to play with DJ mode 
but no music, my console (chrome) shows me error 500 access denied.
Than after a few moments the server is unresponsive and the Webui will not be build up anymore
(probably I have to wait around 7 minutes again) .. 

In console I see this when the UI was responsive

2018-10-25T20:25:03.601Z info: Access mStream on your local network: https://10.1.1.131:3000
TypeError: Cannot read property 'count' of undefined
    at Object.exports.getNumberOfFiles (/home/dennis/mStream/modules/db-read/database-public-loki.js:84:29)
    at /home/dennis/mStream/modules/db-management/database-master.js:16:25
    at Layer.handle [as handle_request] (/home/dennis/mStream/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/dennis/mStream/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/dennis/mStream/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/dennis/mStream/node_modules/express/lib/router/layer.js:95:5)
    at /home/dennis/mStream/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/dennis/mStream/node_modules/express/lib/router/index.js:335:12)
    at next (/home/dennis/mStream/node_modules/express/lib/router/index.js:275:10)
    at jwt.verify (/home/dennis/mStream/modules/login.js:149:7)
TypeError: Cannot read property 'find' of undefined
    at getPlaylists (/home/dennis/mStream/modules/db-read/database-public-loki.js:209:39)
    at mstream.get (/home/dennis/mStream/modules/db-read/database-public-loki.js:95:23)
    at Layer.handle [as handle_request] (/home/dennis/mStream/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/dennis/mStream/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/dennis/mStream/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/dennis/mStream/node_modules/express/lib/router/layer.js:95:5)
    at /home/dennis/mStream/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/dennis/mStream/node_modules/express/lib/router/index.js:335:12)
    at next (/home/dennis/mStream/node_modules/express/lib/router/index.js:275:10)
    at jwt.verify (/home/dennis/mStream/modules/login.js:149:7)
TypeError: Cannot read property 'count' of undefined
    at Object.exports.getNumberOfFiles (/home/dennis/mStream/modules/db-read/database-public-loki.js:84:29)
    at /home/dennis/mStream/modules/db-management/database-master.js:16:25
    at Layer.handle [as handle_request] (/home/dennis/mStream/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/dennis/mStream/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/dennis/mStream/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/dennis/mStream/node_modules/express/lib/router/layer.js:95:5)
    at /home/dennis/mStream/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/dennis/mStream/node_modules/express/lib/router/index.js:335:12)
    at next (/home/dennis/mStream/node_modules/express/lib/router/index.js:275:10)
    at jwt.verify (/home/dennis/mStream/modules/login.js:149:7)

after a restart, no output, I have to wait . until it becomes responsive again.

**Comment by aroundmyroom** [comment]
this is what happens after a restart 

![image](https://user-images.githubusercontent.com/250108/47528763-4ba3d900-d8a6-11e8-9130-2a1e7e1334bb.png)

high load, this issue I had before, but now I have a db which is ok and I just only updated to the latest npm parts and latest code..

**Comment by aroundmyroom** [comment]
ok login issues have to do with probably some caching 
than indeed I need to wait around 9 minutes until the UI has come up. Looks like above CPU usage is causing the webserver not  serving requests

Latest update
playback after the start is looking ok. Jukebox I still have various issues, but that is what i rarely use (even dunno what is the reason to use ;)
so keeps the issue with the webserver only available after around 9 minutes

**Comment by IrosTheBeggar** [comment]
Ok I fixed the problem causing the getNumberOfFiles error

**Comment by IrosTheBeggar** [comment]
Closing this ticket since it's a duplicate of https://github.com/IrosTheBeggar/mStream/issues/144

`(even dunno what is the reason to use ;)`

I use jukebox mode to remotely control my computer with my phone.  I was talking to someone else who uses it to control mstream from IRC and other applications
