### ISSUE TITLE
Crash : TypeError: path must be absolute or specify root to res.sendFile

### ISSUE THREAD

**Issue by spff** [IrosTheBeggar/mStream#152]
```
TypeError: path must be absolute or specify root to res.sendFile
    at ServerResponse.sendFile (/home/spff/Desktop/mStream/node_modules/express/lib/response.js:421:11)
    at mstream.get (/home/spff/Desktop/mStream/mstream.js:62:9)
    at Layer.handle [as handle_request] (/home/spff/Desktop/mStream/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/spff/Desktop/mStream/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/spff/Desktop/mStream/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/spff/Desktop/mStream/node_modules/express/lib/router/layer.js:95:5)
    at /home/spff/Desktop/mStream/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/spff/Desktop/mStream/node_modules/express/lib/router/index.js:335:12)
    at next (/home/spff/Desktop/mStream/node_modules/express/lib/router/index.js:275:10)
    at mstream.use (/home/spff/Desktop/mStream/mstream.js:55:5)
```

I'm using Fedora28, SHA1 494f9d0
```
/usr/bin/mstream -m /d -u spff -x XXXXXXXX -d /home/spff/mstream.db -L /home/spff/Desktop/log/mstream.log
```

**Comment by spff** [comment]
BTW, it told me to remove the bin manually and things went right after I did it, just want to make sure this is the expected behavior.  
```
npm ERR! path /usr/bin/mstream
npm ERR! code EEXIST
npm ERR! Refusing to delete /usr/bin/mstream: ../lib/node_modules/mstream/mstrea                            m-command-line-boot-wrapper.js symlink target is not controlled by npm /usr/bin
npm ERR! File exists: /usr/bin/mstream
npm ERR! Move it away, and try again.
```

**Comment by IrosTheBeggar** [comment]
@spff That's a result of the v4 changes I just pushed. It's expected and should not happen again

**Comment by IrosTheBeggar** [comment]
@spff 

It turns out this bug only appears in linux on not OSX. I just pushed a fix to solve that

**Comment by spff** [comment]
I'll check it out after work = =

**Comment by aroundmyroom** [comment]
i just pulled and got same error

root@boeken:/home/dennis/mStream# npm link
removed 72 packages and audited 819 packages in 8.959s
found 0 vulnerabilities

npm ERR! path /usr/bin/mstream
npm ERR! code EEXIST
npm ERR! Refusing to delete /usr/bin/mstream: ../lib/node_modules/mstream/mstream-command-line-boot-wrapper.js symlink target is not controlled by npm /usr/bin
npm ERR! File exists: /usr/bin/mstream
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-19T07_00_34_589Z-debug.log


also problem: mStream cannot be found anynmore ???
/mStream-data$ /usr/bin/mstream -j /home/dennis/mStream-data/config.json
bash: /usr/bin/mstream: No such file or directory

**Comment by aroundmyroom** [comment]
a remove symlink fixed it .. now looking for the changes, you have old json file ;)

**Comment by spff** [comment]
Things works ! Thanks~~
