### ISSUE TITLE
ReferenceError: scan is not defined

### ISSUE THREAD

**Issue by kierdavis** [IrosTheBeggar/mStream#165]
Switching to the "Database" tab in the web gui and pressing "Build Database" results in this error:

```
 2019-01-11T22:48:11.602Z info: File scan started on /data/music/library
 ReferenceError: scan is not defined
     at mstream.get (/nix/store/vlh165bkhc90d085hn0paizrxqmbcjdx-node-mstream-3.9.1/lib/node_modules/mstream/modules/db-management/database-master.js:92:17)
     at Layer.handle [as handle_request] (/nix/store/vlh165bkhc90d085hn0paizrxqmbcjdx-node-mstream-3.9.1/lib/node_modules/mstream/node_modules/express/lib/router/layer.js:95:5)
     at next (/nix/store/vlh165bkhc90d085hn0paizrxqmbcjdx-node-mstream-3.9.1/lib/node_modules/mstream/node_modules/express/lib/router/route.js:137:13)
     at Route.dispatch (/nix/store/vlh165bkhc90d085hn0paizrxqmbcjdx-node-mstream-3.9.1/lib/node_modules/mstream/node_modules/express/lib/router/route.js:112:3)
     at Layer.handle [as handle_request] (/nix/store/vlh165bkhc90d085hn0paizrxqmbcjdx-node-mstream-3.9.1/lib/node_modules/mstream/node_modules/express/lib/router/layer.js:95:5)
     at /nix/store/vlh165bkhc90d085hn0paizrxqmbcjdx-node-mstream-3.9.1/lib/node_modules/mstream/node_modules/express/lib/router/index.js:281:22
     at Function.process_params (/nix/store/vlh165bkhc90d085hn0paizrxqmbcjdx-node-mstream-3.9.1/lib/node_modules/mstream/node_modules/express/lib/router/index.js:335:12)
     at next (/nix/store/vlh165bkhc90d085hn0paizrxqmbcjdx-node-mstream-3.9.1/lib/node_modules/mstream/node_modules/express/lib/router/index.js:275:10)
     at /nix/store/vlh165bkhc90d085hn0paizrxqmbcjdx-node-mstream-3.9.1/lib/node_modules/mstream/mstream.js:171:7
     at Layer.handle [as handle_request] (/nix/store/vlh165bkhc90d085hn0paizrxqmbcjdx-node-mstream-3.9.1/lib/node_modules/mstream/node_modules/express/lib/router/layer.js:95:5)
 2019-01-11T22:48:14.231Z info: File scan message: database saved
 2019-01-11T22:48:14.241Z info: File scan completed with code 0
```

This is occurring on version 3.9.1, but the [offending line](https://github.com/IrosTheBeggar/mStream/blob/3.9.1/modules/db-management/database-master.js#L92) looks unchanged on master.

I can't see where the `scan` variable used at the site of the error is defined - should it be `res` instead?

**Comment by IrosTheBeggar** [comment]
This is fixed in the master branch. I also pushed the latest version (4.0) to npm

**Comment by kierdavis** [comment]
Thanks, I'm no longer getting this issue on 4.0.0.
