### ISSUE TITLE
PayloadTooLargeError occured when I add over 2k music files in ONE playlist

### ISSUE THREAD

**Issue by KurohaneNioko** [IrosTheBeggar/mStream#179]
> PayloadTooLargeError: request entity too large
    at readStream (/root/mStream/node_modules/raw-body/index.js:155:17)
    at getRawBody (/root/mStream/node_modules/raw-body/index.js:108:12)
    at read (/root/mStream/node_modules/body-parser/lib/read.js:77:3)
    at urlencodedParser (/root/mStream/node_modules/body-parser/lib/types/urlencoded.js:116:5)
    at Layer.handle [as handle_request] (/root/mStream/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/mStream/node_modules/express/lib/router/index.js:317:13)
    at /root/mStream/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/mStream/node_modules/express/lib/router/index.js:335:12)
    at next (/root/mStream/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/root/mStream/node_modules/body-parser/lib/types/json.js:119:7)

PayloadTooLargeError occured when I add over 2k music files in ONE playlist and tried to download the playlist. Maybe it's hard for node.js to process it...

**Comment by IrosTheBeggar** [comment]
That's not surprising.  The server is actually rejecting the message due to the size.  But it would probably crash due to a memory error if that message made it through.

Are you looking to use mStream to sync your files?

**Comment by KurohaneNioko** [comment]
Thx. I just want to enjoy my music files without storing them in my device. Maybe I can try a url playlist to play my music.

**Comment by IrosTheBeggar** [comment]
I’m working on a file sync utility so you won’t need to use the download feature for huge playlists:
https://github.com/IrosTheBeggar/mStream/issues/189
