### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by chipsandtea** [IrosTheBeggar/mStream#2]
Get this error when running mstream in my music directory.

`````` /usr/local/lib/node_modules/mstream/mstream.js:296
  function authenticateUser (req, res, next) {
  ^^^^^^^^
SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3```
``````

**Comment by IrosTheBeggar** [comment]
What OS are you running this on?  Also can you post the command you used to start it?

**Comment by chipsandtea** [comment]
Running CentOS on a VPS. I just ran `mstream` in a directory with a single .mp3 file.

**Comment by IrosTheBeggar** [comment]
Can you check what version of node you are running?  mStream only works on v4 and greater

**Comment by IrosTheBeggar** [comment]
@chipsandtea Any update on this.  Thinking about closing this ticket if I don;t hear back soon
