### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by romjean** [IrosTheBeggar/mStream#207]
Hi,
After installing mstream 4.3.0 on a Synology NAS (with Node.js v6 installed), and when trying to start mstream, I have an error message:

````
/path/to/websocket.js:347
    ...options,
    ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/path/to/node_modules/ws/index.js:3:19)
````

What sould I do ? Change Node version ? It was working perfectly with an older version of mstream express

**Comment by IrosTheBeggar** [comment]
Hi @romjean,

The latest version of mStream requires node v8 or greater. I'm starting to move code to use async/await because node v8 is now in LTS mode

**Comment by romjean** [comment]
Yes, indeed it works with node v8, thanks a lot !
