### ISSUE TITLE
Database scan stops as soon as it encounters a dotfile folder it can't read

### ISSUE THREAD

**Issue by yoasif** [IrosTheBeggar/mStream#209]
I have a .snapshots folder inside of my music directory, as I am using snapper to take snapshots of my music folder for resiliency purposes.

This folder is owned by root (not the same user that mstream is running as). 

Log:

```
2019-10-05T04:37:09.234Z info: Access mStream locally: http://localhost:3000
2019-10-05T04:37:09.236Z info: Try the WinAmp Demo: http://localhost:3000/winamp
2019-10-05T04:37:24.259Z info: File scan started on /music
2019-10-05T04:37:24.409Z error: File scan error: fs.js:114
    throw err;
    ^

Error: EACCES: permission denied, scandir '/music/.snapshots'
    at Object.readdirSync (fs.js:790:3)
    at recursiveScan (/opt/mstream/modules/db-management/database-default-manager.js:93:20)
    at recursiveScan (/opt/mstream/modules/db-management/database-default-manager.js:106:7)
    at scanDirectory (/opt/mstream/modules/db-management/database-default-manager.js:60:3)
    at scanDirectory.next (<anonymous>)
    at dbRead.setup (/opt/mstream/modules/db-management/database-default-manager.js:54:25)
    at filesdb.loadDatabase.err (/opt/mstream/modules/db-write/database-default-loki.js:26:5)
    at /opt/mstream/node_modules/lokijs/src/lokijs.js:2626:15
    at loadDatabaseCallback (/opt/mstream/node_modules/lokijs/src/lokijs.js:2548:15)
    at /opt/mstream/node_modules/lokijs/src/lokijs.js:2353:11

2019-10-05T04:37:24.411Z info: File scan completed with code 1

```
No file is present in the db folder once this happens.

It'd be nice if mstream ignored folders it doesn't have access to, or if I could tell it not to scan that folder.

**Comment by IrosTheBeggar** [comment]
The latest commit should fix this

**Comment by yoasif** [comment]
That fixed it.
