### ISSUE TITLE
Strange permission issue

### ISSUE THREAD

**Issue by alfureu** [IrosTheBeggar/mStream#233]
Running mStream from docker (`linuxserver/mstream` version), with PUID=1000 and PGID=100. Whenever I start the container, I receive the following error in logs:

```
  v4.5.2     ____  _
   _ __ ___ / ___|| |_ _ __ ___  __ _ _ __ ___
  | '_ ` _ \\___ \| __| '__/ _ \/ _` | '_ ` _ \
  | | | | | |___) | |_| | |  __/ (_| | | | | | |
  |_| |_| |_|____/ \__|_|  \___|\__,_|_| |_| |_|
  Paul Sori - paul@mstream.io

Find a bug? Report it at:
https://github.com/IrosTheBeggar/mStream/issues

4
    throw err;
    ^

Error: EACCES: permission denied, mkdir '/root/.ffbinaries-cache'
    at Object.mkdirSync (fs.js:757:3)
    at ensureDirSync (/opt/mstream/node_modules/ffbinaries/ffbinaries-lib.js:26:9)
    at Object.<anonymous> (/opt/mstream/node_modules/ffbinaries/ffbinaries-lib.js:30:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)

```
What I am able to identify is that the issue is related with the transcode section in config.json, particularly with the path to ffmpeg. I installed to alpine linux (inside of the docker image) ffmpeg, but mstream still cannot find it. 

I tried with both paths 

```
root@22cfe32a9a12:/# whereis ffmpeg
ffmpeg: /usr/bin/ffmpeg /usr/share/ffmpeg
```

Could you help?

EDIT: updated log for more detail and more info

**Comment by Byter09** [comment]
I just tried to add
```json
"transcode": {
    "enabled": true,
    "defaultCodec": "opus",
    "defaultBitrate": "128k"
  },
```
as well and this started popping up.

**Comment by henrikp** [comment]
Are you running a Raspberry Pi with an 64-bit enivronment (arm64) perhaps, like I am? The current "ffbinaries" script doesn't include arm64 support while the binaries are available on that site that they are using. Opened up a an issue as well: [https://github.com/ffbinaries/ffbinaries-node/issues/34](url)
In the mean time: you have to download a static arm64 binary pack from [https://www.johnvansickle.com/ffmpeg/](url) and replace /ffmpeg in the container via volume mounting.

**Comment by IrosTheBeggar** [comment]
This has been fixed by the linuxserver team. I don't have a arm64 board to test this on though. I can confirm ffmpeg works on my x64 machine
