### ISSUE TITLE
Installation issue on Ubuntu 16.04

### ISSUE THREAD

**Issue by mcdoh** [IrosTheBeggar/mStream#24]
I've not been able to install via npm on my Ubuntu 16.04 machine. The logs lists a 404 on bcrypt but I'm able to curl it without issue. There is a complaint about root not having access to ~/.nod-gyp/6.10.3 but it appears that the problem is the directory just doesn't exist. I'm looking forward to checking out mStream, Thanks!

```
$ sudo npm install -g mstream
/usr/bin/mstream -> /usr/lib/node_modules/mstream/mstream-command-line-boot-wrapper.js

> bcrypt@1.0.2 install /usr/lib/node_modules/mstream/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v48-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@6.10.3 (node-v48 ABI) (falling back to source compile with node-gyp)
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/gavin/.node-gyp/6.10.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/mstream/node_modules/bcrypt/.node-gyp"
make: Entering directory '/usr/lib/node_modules/mstream/node_modules/bcrypt/build'
make: *** No rule to make target '../.node-gyp/6.10.3/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/lib/node_modules/mstream/node_modules/bcrypt/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-72-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/mstream/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/usr/lib/node_modules/mstream/node_modules/bcrypt/lib/binding"
gyp ERR! cwd /usr/lib/node_modules/mstream/node_modules/bcrypt
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/mstream/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/usr/lib/node_modules/mstream/node_modules/bcrypt/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/mstream/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:886:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.0-72-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/mstream/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/mstream/node_modules/bcrypt
node-pre-gyp ERR! node -v v6.10.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/mstream/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/usr/lib/node_modules/mstream/node_modules/bcrypt/lib/binding' (1)
/usr/lib
└── (empty)

npm ERR! Linux 4.4.0-72-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "mstream"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@1.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@1.0.2 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gavin/npm-debug.log
npm ERR! code 1
```

**Comment by mcdoh** [comment]
Looks like the issue is just with installing bcrypt. Sorry.

**Comment by IrosTheBeggar** [comment]
Bcrypt has given me some grief in the past as well.  Did you install node-gyp & build-essentials for ubuntu before installing mstream?

**Comment by mcdoh** [comment]
Yes, I had installed node-gyp and build-essentials. Instead of the npm install I just cloned the repo and installed locally. I think I still saw some bcrypt errors but mStream ran fine.
