### ISSUE TITLE
Error: Cannot find module 'strtok3/lib/type'

### ISSUE THREAD

**Issue by eatmorehumans** [IrosTheBeggar/mStream#242]
Getting this after installing on Ubuntu via: 
npm install -g mstream
npm link

The mStream web app seems to work fine. I did notice that in ~/mStream-4.6.0/node_modules/strtok3 there is a types.js but no type.js. I copied types.js to type.js and types-d.ts to type-d.ts for good measure and the launch errors went away. My node-fu is not so good, but maybe this is a problem that should be fixed?

  v4.6.0     ____  _
   _ __ ___ / ___|| |_ _ __ ___  __ _ _ __ ___
  | '_ ` _ \\___ \| __| '__/ _ \/ _` | '_ ` _ \
  | | | | | |___) | |_| | |  __/ (_| | | | | | |
  |_| |_| |_|____/ \__|_|  \___|\__,_|_| |_| |_|
  Paul Sori - paul@mstream.io

Find a bug? Report it at:
https://github.com/IrosTheBeggar/mStream/issues

2020-01-12T13:54:11.089Z info: Access mStream locally: http://localhost:3000
2020-01-12T13:54:11.090Z info: Try the WinAmp Demo: http://localhost:3000/winamp
2020-01-12T13:54:14.102Z info: File scan started on /home/mstream/mStream-4.6.0
2020-01-12T13:54:14.630Z error: File scan error: module.js:549
    throw err;
    ^

Error: Cannot find module 'strtok3/lib/type'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/mstream/mStream-4.6.0/node_modules/music-metadata/lib/aiff/AiffParser.js:5:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

2020-01-12T13:54:14.635Z info: File scan completed with code 1

**Comment by IrosTheBeggar** [comment]
I noticed the music-metadata package was really outdated, which might have been causing this.  Try pulling the latest version (4.6.1) to see if that works

**Comment by IrosTheBeggar** [comment]
@eatmorehumans 

I haven't been able to replicate this bug.  Have you been able to confirm the update to music-metadata fixed this?
