### ISSUE TITLE
Issue starting mStream for first time - SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by Mr-Chimp** [IrosTheBeggar/mStream#299]
Hi, I have set-up mStream using the 'install from command line' instructions and when I go to run the application I get the following error when I try to start with or without a config file:

/home/airsonic/mStream/mstream.js:22
exports.serveIt = async configFile => {
                         ^^^^^^^^^^ ##Note - These are under configFile, getting the position correct was hard 

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/airsonic/mStream/cli-boot-wrapper.js:45:1)

Cheers for any assistance

**Comment by IrosTheBeggar** [comment]
What version of nodeJS are you running?

**Comment by Mr-Chimp** [comment]
I am running node v6.17.1

**Comment by IrosTheBeggar** [comment]
Try upgrading to the latest version of NodeJS.  mStream requires v10 or greater

**Comment by Mr-Chimp** [comment]
Ahh yeh upgrading sorted it. I was on CentOS 7 and had installed it via package manager. 

Thanks very much
