### ISSUE TITLE
BUG: db error

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#313]
2021-05-08T09:26:09.419Z info: File scan message: database saved
2021-05-08T09:26:12.731Z info: File scan completed with code null
2021-05-08T21:04:51.597Z error: Db Error
SyntaxError: Invalid regular expression: /Prize Of Beauty Mix)/: Unmatched ')'
    at new RegExp (<anonymous>)
    at precompileQuery (/home/mStream/node_modules/lokijs/src/lokijs.js:3393:19)
    at Resultset.find (/home/mStream/node_modules/lokijs/src/lokijs.js:3525:17)
    at Resultset.findAnd (/home/mStream/node_modules/lokijs/src/lokijs.js:3425:14)
    at Resultset.find (/home/mStream/node_modules/lokijs/src/lokijs.js:3498:23)
    at Collection.find (/home/mStream/node_modules/lokijs/src/lokijs.js:7057:27)
    at searchByX (/home/mStream/src/api/db.js:259:44)
    at mstream.post (/home/mStream/src/api/db.js:234:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

it looked like a scan issue, but it was a search issue .. I probably tried to find something but it gave underwater an error. I initially thought it was an scan db issue ..

**Comment by IrosTheBeggar** [comment]
What did you search for that triggered this?

**Comment by aroundmyroom** [comment]
I believe: expression: Prize Of Beauty Mix)

**Comment by IrosTheBeggar** [comment]
I made an update that should fix this. You will need to run `npm install` on this update

**Comment by aroundmyroom** [comment]
its fixed
