### ISSUE TITLE
Unable to read a public playslist with FLAC.

### ISSUE THREAD

**Issue by Tiritibambix** [IrosTheBeggar/mStream#393]
Using docker, [linuxserver/mstream](https://github.com/linuxserver/docker-mstream)

Tried to share a 4 songs playlist.

```
2022-11-14T19:50:48.048Z error: Server error on route /media/library/[...]xxx.flac?token=longtoken
WebError: Authentication Error
    at /opt/mstream/src/api/auth.js:88:15
    at Layer.handle [as handle_request] (/opt/mstream/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/mstream/node_modules/express/lib/router/index.js:328:13)
    at /opt/mstream/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/opt/mstream/node_modules/express/lib/router/index.js:346:12)
    at next (/opt/mstream/node_modules/express/lib/router/index.js:280:10)
    at SendStream.error (/opt/mstream/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (node:events:513:28)
    at SendStream.error (/opt/mstream/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/opt/mstream/node_modules/send/index.js:417:12)
```

Can't a playlist be shared publicly ?

**Comment by Tiritibambix** [comment]
> Can't a playlist be shared publicly ?

2 months later I gave it another try.

Apparently, I can share a song / playlist that is / has mp3 files. Flac seems to be the problem here. Can't download it either.
