### ISSUE TITLE
mstream fails to play song on Chrome and Firefox

### ISSUE THREAD

**Issue by laker-93** [IrosTheBeggar/mStream#394]
First, thanks for developing this software! I am unable to play audio with mstream from the browser of my office computer. At first I thought the error could be due to the client since it works fine on the browser on my phone. However the error seems to be server side; I'm getting a 503 HTTP error code. The UI loads fine but when I attempt to play a song, the UI shows a "Failed to play song" error message. Further logs provided below. I would love to get a solution on this, apart from this issue mstream works great in the browser.

Chrome version: Version 107.0.5304.88 (Official Build) (64-bit)

Firefox version: Version 107.0.5304.88 (Official Build) (64-bit)

FIREFOX CONSOLE LOG

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/14069946/203745461-a52e3b9e-6b19-4483-988f-2a2bf4439343.png">

SERVER LOG

{"level":"error","message":"Server error on route /api/v1/admin/file-explorer/win-drives","stack":{"name":"WebError","status":401},"timestamp":"2022-11-23T08:28:25.660Z"}

DOCKER LOG
 
2022-11-23T08:28:25.659Z error: Server error on route /api/v1/admin/file-explorer/win-drives
WebError: Authentication Error                                                            
    at /opt/mstream/src/api/auth.js:54:25
    at Layer.handle [as handle_request] (/opt/mstream/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/mstream/node_modules/express/lib/router/index.js:328:13)
    at /opt/mstream/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/opt/mstream/node_modules/express/lib/router/index.js:346:12)
    at next (/opt/mstream/node_modules/express/lib/router/index.js:280:10)    
    at SendStream.error (/opt/mstream/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (node:events:513:28)
    at SendStream.error (/opt/mstream/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/opt/mstream/node_modules/send/index.js:417:12)

**Comment by laker-93** [comment]
I have mstream deployed using: https://github.com/linuxserver/docker-mstream
