### ISSUE TITLE
Sporadic database error

### ISSUE THREAD

**Issue by pR0Ps** [IrosTheBeggar/mStream#41]
I used the Dockerfile I made in #40 to set up an instance and this error usually happened after a few minutes of playing around with the UI.

```
/mstream/node_modules/sqlite3/lib/trace.js:27
                    throw err;
                    ^

TypeError: Cannot read property 'Count(*)' of undefined
    at Statement.<anonymous> (/mstream/modules/db-read/database-public-sqlite.js:15:17)
--> in Database#get('SELECT Count(*) FROM items WHERE user = ?;', [ 'mstream-user' ], [Function])
    at Object.exports.getNumberOfFiles (/mstream/modules/db-read/database-public-sqlite.js:14:6)
    at /mstream/modules/db-management/database-master.js:112:25
    at Layer.handle [as handle_request] (/mstream/node_modules/express/lib/router/layer.js:95:5)
    at next (/mstream/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/mstream/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/mstream/node_modules/express/lib/router/layer.js:95:5)
    at /mstream/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/mstream/node_modules/express/lib/router/index.js:335:12)
    at next (/mstream/node_modules/express/lib/router/index.js:275:10)
```

**Comment by IrosTheBeggar** [comment]
Thanks for updating the Docker file and reporting this.  I'm currently putting 100% of my effort behind the android app right now, so it might be a few days before I get back to this

**Comment by Riajyuu** [comment]
@IrosTheBeggar Just a little bit question here: may I list your app into my Android list as well? https://github.com/AmazingApps/Amazing-Android-Apps

Yes, we are now an Org including all platforms :-)

**Comment by IrosTheBeggar** [comment]
@EMLVIRUS 

Sure

**Comment by IrosTheBeggar** [comment]
The latest version of mStream has dropped SQLite in favor of LokiJS.  This should prevent any more problems like this
