### ISSUE TITLE
problems since last update

### ISSUE THREAD

**Issue by brazzmonkey** [IrosTheBeggar/mStream#431]
mStrean is broken for me at the moment.
I get:

> Jun  7 19:30:36  node[6616]: Started Music Mstream Server.

> Jun  7 19:30:36  node[6616]: v5.12.2
> Jun  7 19:30:36  node[6616]: Check out our Discord server:
> Jun  7 19:30:36  node[6616]: https://discord.gg/AM896Rr
> Jun  7 19:30:37  node[6616]: /home/XXXXXXXXXXXXXX/mStream/node_modules/glob/node_modules/minimatch/dist/commonjs/ast.js:86
> Jun  7 19:30:37  node[6616]:     #fillNegs() {
> Jun  7 19:30:37  node[6616]:              ^
> Jun  7 19:30:37  node[6616]: SyntaxError: Unexpected token '('
> Jun  7 19:30:37  node[6616]:     at wrapSafe (internal/modules/cjs/loader.js:915:16)
> Jun  7 19:30:37  node[6616]:     at Module._compile (internal/modules/cjs/loader.js:963:27)
> Jun  7 19:30:37  node[6616]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
> Jun  7 19:30:37  node[6616]:     at Module.load (internal/modules/cjs/loader.js:863:32)
> Jun  7 19:30:37  node[6616]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
> Jun  7 19:30:37  node[6616]:     at Module.require (internal/modules/cjs/loader.js:887:19)
> Jun  7 19:30:37  node[6616]:     at require (internal/modules/cjs/helpers.js:74:18)
> Jun  7 19:30:37  node[6616]:     at Object.<anonymous> (/home/XXXXXXXXXXXXXXXX/mStream/node_modules/glob/node_modules/minimatch/dist/commonjs/index.js:9:18)
> Jun  7 19:30:37  node[6616]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
> Jun  7 19:30:37  node[6616]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
> Jun  7 19:30:37  systemd[1]: mstream.service: Main process exited, code=exited, status=1/FAILURE
> Jun  7 19:30:37  systemd[1]: mstream.service: Failed with result 'exit-code'.
> Jun  7 19:30:37  systemd[1]: mstream.service: Scheduled restart job, restart counter is at 5.
> Jun  7 19:30:37  systemd[1]: Stopped Music Mstream Server.
> Jun  7 19:30:37  systemd[1]: mstream.service: Start request repeated too quickly.
> Jun  7 19:30:37  systemd[1]: mstream.service: Failed with result 'exit-code'.
> Jun  7 19:30:37  systemd[1]: Failed to start Music Mstream Server.

running an up-to-date Ubuntu 22.04
Any guidance would be appreciated, 
thanks

**Comment by brazzmonkey** [comment]
for the record, I solved it by updating to latest node from source, using https://github.com/nodesource/distributions
best regards
