### ISSUE TITLE
 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by gerroon** [IrosTheBeggar/mStream#56]
Hi

I installed it on Debian Testing x64 

I followed your guide.

thanks

mstream
USER SYSTEM NOT ENABLED!
SSL DISABLED
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:3000
    at Object._errnoException (util.js:1019:11)
    at _exceptionWithHostPort (util.js:1041:20)
    at Server.setupListenHandle [as _listen2] (net.js:1344:14)
    at listenInCluster (net.js:1385:12)
    at Server.listen (net.js:1469:7)
    at Object.exports.serveit (/media/REPOC/BUILD/mStream/mstream.js:170:10)
    at Object.<anonymous> (/media/REPOC/BUILD/mStream/mstream-command-line-boot-wrapper.js:15:9)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)

**Comment by gerroon** [comment]
I think I had the issue because I was using node8 :(

**Comment by IrosTheBeggar** [comment]
The EADDRINUSE error happens when you're using a port that's already being used.  Try setting mStream to another port with the `-p` flag
