### ISSUE TITLE
Startup with config.json only does not work

### ISSUE THREAD

**Issue by espenaf** [IrosTheBeggar/mStream#75]
When trying to startup mstream with only configuration via a config.json file the application crashes with:

events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1496:7)
    at Object.exports.serveit (/usr/lib/node_modules/mstream/mstream.js:170:10)
    at Object.<anonymous> (/usr/lib/node_modules/mstream/mstream-command-line-boot-wrapper.js:15:9)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)

My config.json looks like this:

`
{
  "port": 3030,
  "database_plugin":{
    "dbPath":"/var/lib/mstream/mstream.db"
  },
  "folders": {
    "media": "/var/lib/mstream/music"
  }
}
`

mstream starts up without problem if I add the -m option.

**Comment by IrosTheBeggar** [comment]
Right now the config file needs users in order to work.  I'll leave this ticket open until I fix that

**Comment by IrosTheBeggar** [comment]
You're error specifically is about port 3000 being in use.  I'm guessing this is because you're config.json is not being loaded. When using a JSON config, it should be the only argument in your command.  Like `mstream config.json`

Let me know if this helps.

**Comment by IrosTheBeggar** [comment]
You can also now have a config.json without a user object.  Closing ticket
